modelproject/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout, name = 'logout')
]

modelproject/blog/urls.py
# app폴더 urls.py
# urls.py에서 blog앱에서 사용하는 url을 모두 가져옵니다.

from django.urls import path
from . import views #현재 폴더에 있는 views에 접근하기 때문

app_name = 'blog' # app_name에는 앱 이름을 넣어줍니다.

urlpatterns = [
    path('<int:id>', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path("update/<int:id>", views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('newreply', views.newreply, name='newreply'),
    path('replydelete/<int:id>', views.replydelete, name="replydelete"),
]

modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name = 'home'),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls'))
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modelproject/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    nickname = models.CharField(max_length=100)
    university = models.CharField(max_length = 50)

modelproject/blog/models.py
from tkinter import CASCADE
from django.db import models
from account.models import CustomUser

# Create your models here.
class Blog(models.Model):
    user = models.ForeignKey(CustomUser, null = True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=10)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="blog/", blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

class Comment(models.Model):
    blog = models.ForeignKey(Blog, null = True, on_delete=models.CASCADE, related_name="comments")
    comment_user = models.ForeignKey(CustomUser, null=True, on_delete=models.CASCADE)
    comment_body = models.CharField(max_length=200)
    comment_date = models.DateTimeField()
    class Meta:
        ordering = ['comment_date']

modelproject/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'nickname', 'university']

modelproject/blog/forms.py
from dataclasses import fields
from django import forms
from .models import Blog,Comment

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'writer', 'body', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_body']

modelproject/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import auth
from .forms import SignupForm

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(
                request=request,
                username=username,
                password=password
            )

            if user is not None:
                auth.login(request, user)
                return redirect('home')
        return redirect('account:login')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form' : form})

def logout(request):
    auth.logout(request)
    return redirect('home')

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('home')
        return redirect('account:signup')
    else:
        form = SignupForm()
        return render(request, 'signup.html', {'form' : form})

modelproject/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Blog,Comment,CustomUser
from .forms import BlogForm,CommentForm
from django.core.paginator import Paginator


# Create your views here.
def home(request):
    blogs = Blog.objects.order_by('-pub_date')
    query = request.GET.get('query')
    if query:
        blogs = Blog.objects.filter(title__contains=query)
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    paginated_blogs = paginator.get_page(page)
    return render(request, 'home.html', {'blogs' : paginated_blogs})

def detail(request, id):
    blog = get_object_or_404(Blog, pk = id)
    return render(request, 'detail.html', {'blog' : blog})

def new(request):
    form = BlogForm()
    return render(request, 'new.html', {'form': form})

def create(request):
    form = BlogForm(request.POST, request.FILES)
    if form.is_valid():
        new_blog = form.save(commit=False)
        new_blog.pub_date = timezone.now()
        if request.user.is_authenticated:
            new_blog.user = request.user
        new_blog.save()
        return redirect('blog:detail', new_blog.id)
    return redirect('home')

def update(request, id):
    blog = Blog.objects.get(id = id)
    if request.method == 'POST':
        blog.title = request.POST['title']
        blog.body = request.POST['body']
        blog.save()
        return redirect('blog:detail', blog.id)
    return render(request, 'update.html', {'blog' : blog})

def delete(request, id):
    blog = Blog.objects.get(id = id)
    blog.delete()
    return redirect('home')

def newreply(request):
    if request.method == "POST":
        comment = Comment()
        comment.comment_body = request.POST['comment_body']
        comment.blog = Blog.objects.get(pk=request.POST['blog'])
        author = request.POST['user']
        print(type(author), author)
        if author:
            comment.comment_user = CustomUser.objects.get(username=author)
        else:
            return redirect('blog:detail', comment.blog.id)
        comment.comment_date = timezone.now()
        comment.save()

        return redirect('blog:detail', comment.blog.id)
    else:
        return redirect('home')

def replydelete(request, id):
    comment = get_object_or_404(Comment, pk=id)
    blog_id = comment.blog.id
    comment.delete()
    return redirect('blog:detail', blog_id)

modelproject/account/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">로그인 페이지</h1>
<form action="{% url 'account:login' %}" method="POST" style="text-align: center; vertical-align:middle;">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">로그인</button>
</form>

{% endblock %}

modelproject/account/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">회원가입 페이지</h1>
<form action="{% url 'account:signup' %}" method="POST" style="text-align: center;">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" >회원가입</button>
</form>
{% endblock %}

modelproject/blog/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <title>Detail</title>
  <body>
    <div class="container" style="text-align: center;">
        <h1>{{ blog.title }}</h1>
        <p>유저: {{blog.user.username}}</p>
        <p>{{ blog.pub_date }}</p>
        <p>{{ blog.body }}</p>
        {% if blog.image %}
        <p><img src="{{blog.image.url}}" alt="" style="text-align: center;"/></p>
        {% endif %}
        {% if blog.user == user %}
        <a href="{% url 'blog:update' blog.id %}">수정하기</a>
            <a href="{% url 'blog:delete' blog.id%}">Delete Post</a>
        {% endif %}
        <a href="{% url 'home' %}">돌아가기</a>
        <form method="POST" action="/blog/newreply">
          {% csrf_token %}
          <input type="hidden" value="{{blog.id}}" name="blog" />
          <input type="hidden" value="{{user.username}}" name="user" />
          댓글 작성 : <input type="text" name="comment_body" />
          <button type="submit" class="btn btn-secondary">작성</button>
        </form>
      
        {% for comment in blog.comments.all %}

        <p><span> {{comment.comment_user}} </span> : {{ comment.comment_body }}</p>
        {% if comment.comment_user == user %}
  <a href="{% url 'blog:replydelete' comment.id %}"
    ><input type="button" value="delete"
  /></a>
  {% endif %}
        <p>위 댓글을 단 시간 : {{comment.comment_date}}</p>

        {% endfor %}
    </div>
  </body>
{% endblock %}

modelproject/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <div class = 'block1'>
      <header>
        
          {% if user.is_authenticated %}
          <h1>Blog &nbsp;&nbsp;<a href="{% url 'blog:new' %}">
          <img src="{% static 'before.JPEG' %}" 
            onmouseover="this.src='{% static 'after.JPEG' %}'"
            onmouseout="this.src='{% static 'before.JPEG' %}'" 
            style="width: 75px; height: 75px; float: right;">
          </a></h1>
          {% else %}
          <h1>Blog</h1>
      </header>
      

      <br>
      {% endif %}
      {% for blog in blogs %}
      <div class="box" style="margin-top :80px;">
      <div class="img" style="">
        <a href="{% url 'blog:detail' blog.id %}">
          {% if blog.image %}
          <img src="{{blog.image.url}}" alt="" style="float: right; width:75px; height: 75px;" >
        </a>
          {% else %}
          <img src="{% static 'nosign.png' %}" alt="" style="width: 75px; height: 75px; float: right;">
        </a>

        {% endif %}
        <div class="content">
          <h3>{{ blog.title }}</h3>
          <b>작성자: {{ blog.user }} / 작성내용: {{ blog.summary }} <a href="{% url 'blog:detail' blog.id %}">..더보기</a></b><br>
         
        </div>
      </div>
      {% endfor %}
      <br>
      <br>
      <div class="paginator">
        {% if blogs.has_previous %}
        <a href="?page=1">처음</a>
        <a href="?page={{blogs.previous_page_number}}">이전</a>
        {% endif %}
        <span>{{blogs.number}}</span>
        <span>of</span>
        <span>{{blogs.paginator.num_pages}}</span>
        {% if blogs.has_next %}
        <a href="?page={{blogs.next_page_number}}">다음</a>
        <a href="?page={{blogs.paginator.num_pages}}">마지막</a>
        {% endif %}
      </div>
      </div>
    {% endblock %}

modelproject/blog/templates/new.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">새 글 쓰기</h1>

<form action="{%url 'blog:create'%}" method="post" enctype="multipart/form-data" style="text-align: center;">
    {%csrf_token%}

    {{form.as_p}}
    <button type='submit'>작성 완료</button>
</form>
{% endblock %}

modelproject/blog/templates/update.html
{% extends 'base.html' %}
    {% block content %}
<form action="{% url 'blog:update' blog.id %}" method = "POST" style="text-align: center;">
    {% csrf_token %}
<h4>제목: </h4>
<input type="text" name="title" value={{blog.title}}>
<br>
<br>
<h4>본문: </h4>
<textarea name="body" cols="30" rows="10">{{blog.body}}</textarea><br><br>
<input type="submit" value="완료">
</form>
{% endblock %}

modelproject/modelproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>BLOG</title>
    <style>
      body {

        height: 100%;
        font-family: 'Noto Sans KR', sans-serif;
        }
      a {
        text-decoration: none;
      }
      .block1 {
        margin-top: 20px;
        margin-left: 33%;
        margin-right: 33%;
      }
      .paginator{
        text-align: center;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'IMG_1939.JPG' %}" alt = "" style="width:50px; height: 50px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:new' %}">새 글 쓰기</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'account:login' %}">글을 쓰려면 로그인하세요</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="#">
                {% if user.is_authenticated %}
                {{user.university}}다니는 {{user.nickname}}님 안녕하세요!
                {% endif %}
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}" tabindex="-1" aria-disabled="true">로그아웃</a>
            </li>

            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}" tabindex="-1" aria-disabled="true">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:signup' %}" tabindex="-1" aria-disabled="true">회원가입</a>
              </li>
            {% endif %}
          </ul>
          <form class="d-flex" action="{% url 'home' %}">
            <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name = 'query'>
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="block">

        {% block content %}
        {% endblock %}

      </div>
    </div>
  </body>
  
</html>